### ISSUE TITLE
[TODO] (Breaking) changes for the 1.19 update

### ISSUE THREAD

**Issue by Autovw** [Autovw/AdvancedNetherite#17]
- [x] Remove deprecated ``Tooltips`` API class (replaced by ``TooltipBuilder``)
- [x] Remove other deprecated methods
- [ ] Implement ``IAdvancedItem`` into ``AdvancedArmorItem`` and replace the current hooks with the ones provided by the interface
- [x] Move registry classes from ``core`` to ``core.registry``
- [x] Move utility classes from ``core`` to ``core.util``
- [x] Move ``ModTooltips`` to ``core.util`` and remove deprecated methods within the class
- [x] Completely remove ``content`` package and classes within the package
- [x] Rename subfolders of ``assets/textures`` to be non-plural

**Comment by Autovw** [comment]
[1.13.0-1.19](https://github.com/Autovw/AdvancedNetherite/releases/tag/1.13.0-1.19)
